### ISSUE TITLE
Sql database

### ISSUE THREAD

**Issue by greatwebber** [Rajendra1112/Farmmart#1]
hello, please can i get the sql database pls

**Comment by Rajendra1112** [comment]
[farmmanagement  sql.zip](https://github.com/Rajendra1112/Farmmart/files/13761220/farmmanagement.sql.zip)


> hello, please can i get the sql database pls

[farmmanagement  sql.zip](https://github.com/Rajendra1112/Farmmart/files/13761222/farmmanagement.sql.zip)

**Comment by Rajendra1112** [comment]
> hello, please can i get the sql database pls

[farmmanagement  sql.zip](https://github.com/Rajendra1112/Farmmart/files/13761225/farmmanagement.sql.zip)
